In [12]:
import numpy
list1 = [9,1,3]
list2 = [9,7,5,6,2,3,6]
len1 = len(list1)
len2 = len(list2)
table = numpy.zeros(shape=(len1+1,len2+1))
final = []

#定義遞迴函數
def rec(i,j):
    if i == -1 or j == -1:
        return 0
    if list1[i] == list2[j]:
        return rec(i-1,j-1)+1
    else: 
        return max(rec(i,j-1),rec(i-1,j))
#用遞迴函數做出table
for i in range(0,len1):
    for j in range(0,len2):
        table[i+1][j+1] = rec(i,j)  
print(table)

#找到LCS
for i in range(len1,0,-1):
    while j>0:
        if table[i][j]>table[i][j-1] and table[i][j]>table[i-1][j]:
            final.append(list1[i-1])
            j=j-1
            break
        if table[i][j]>table[i][j-1] and table[i][j] == table[i-1][j]:
            break
        j = j-1
final.reverse()
print(final)     
#用遞迴函數如果list的長度太長時間會大幅提升

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 2. 2.]]
[9, 3]
