In [2]:
import numpy
list1 = [9,1,3]
list2 = [9,7,5,6,2,3,6]
len1 = len(list1)+1
len2 = len(list2)+1
table = numpy.zeros(shape=(len1,len2))
final = []

#迴圈做出table
for i in range(1,len1):
    for j in range(1,len2):
        if list1[i-1] == list2[j-1]:
            table[i][j] = table[i-1][j-1]+1;
        else:
            table[i][j] = max(table[i-1][j],table[i][j-1])
print(table)




j = len2-1



#找到LCS
for i in range(len1-1,0,-1):
    while j>0:
        if table[i][j]>table[i][j-1] and table[i][j]>table[i-1][j]:
            final.append(list1[i-1])
            j=j-1
            break
        if table[i][j]>table[i][j-1] and table[i][j] == table[i-1][j]:
            break
        j = j-1
final.reverse()
print(final)        
#用迴圈list長度可以很長

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 2. 2.]]
[9, 3]
